version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_MULTIPLE_DATABASES=banking_kata_db,keycloak_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - '5400:5432'
    networks:
      - local
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./src/main/resources/postgres/:/docker-entrypoint-initdb.d
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express #TODO: Perhaps explicit version?
    container_name: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=${ME_CONFIG_MONGODB_SERVER}
  adminer:
    image: adminer:4.8.1
    container_name: adminer
    restart: always
    ports:
      - '9000:8080'
    networks:
      - local
    depends_on:
      - postgres

  keycloak:
    image: jboss/keycloak:16.0.0 # NOTE: Custom image build working on Mac M1 (https://github.com/docker/for-mac/issues/5310)
    container_name: keycloak
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak_db
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/realm-export.json
    ports:
      - "10000:8080"
    restart: unless-stopped
    networks:
      - local
    volumes:
      - ./src/main/resources/keycloak/realm-export.json:/tmp/realm-export.json
    depends_on:
      - postgres

volumes:
  postgres:
    driver: local

networks:
  local:
