spring:

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_REALM_URL}
          jwk-set-uri: ${KEYCLOAK_REALM_URL}/protocol/openid-connect/certs

  data:
    mongodb:
      authentication-database: admin
      username: ${MONGO_INITDB_ROOT_USERNAME}
      password: ${MONGO_INITDB_ROOT_PASSWORD}
      database: ${ME_CONFIG_MONGODB_SERVER}
      port: 27017
      host: localhost


# TODO: VC: DELETE This is temporary due to BankingProviderContractTest not working without this

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    show-sql: false
    hibernate-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true