spring:

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_REALM_URL}
          jwk-set-uri: ${KEYCLOAK_REALM_URL}/protocol/openid-connect/certs

  data:
    mongodb:
      authentication-database: admin
      username: ${MONGO_INITDB_ROOT_USERNAME}
      password: ${MONGO_INITDB_ROOT_PASSWORD}
      database: ${ME_CONFIG_MONGODB_SERVER}
      port: 27017
      host: localhost