name: CI
on: [push, pull_request]
jobs:
  build-job:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres_db
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres_usr
          POSTGRES_PASSWORD: postgres_pwd
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

      mongodb:
        image: mongo
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: rootuser
          MONGO_INITDB_ROOT_PASSWORD: rootpass

      mongo-express:
        image: mongo-express
        ports:
          - 8081:8081
        env:
          ME_CONFIG_MONGODB_ADMINUSERNAME: rootuser
          ME_CONFIG_MONGODB_ADMINPASSWORD: rootpass
          ME_CONFIG_MONGODB_SERVER: mongodb


    steps:
      - name: Update Packages
        run:
          sudo apt-get update
      - name: Install Postgresql client
        run:
          sudo apt-get install --yes postgresql-client
      - name: Check database connectivity
        run: psql -h localhost -d postgres_db -U postgres_usr -c 'SELECT 1;'
        env:
          PGPASSWORD: postgres_pwd
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Gradle Build
        run: ./gradlew build
        env:
          POSTGRES_URL: jdbc:postgresql://localhost:5432/postgres_db
          POSTGRES_USER: postgres_usr
          POSTGRES_PASSWORD: postgres_pwd
          MONGO_USER: rootuser
          MONGO_PASSWORD: rootpass
          MONGO_DB: mongo_db
          KEYCLOAK_REALM_URL: http://localhost:10000/auth/realms/banking-kata
          KEYCLOAK_TEST_CLIENT_ID: test-client
          KEYCLOAK_TEST_CLIENT_SECRET: XXXX