name: CI
on: [push, pull_request]
jobs:
  build-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose --env-file=.env.local up -d
      - name: Update Packages
        run:
          sudo apt-get update
      - name: Install Postgresql client
        run:
          sudo apt-get install --yes postgresql-client
      - name: Check database connectivity
        run: psql -h localhost -d banking_kata -U postgres -c 'SELECT 1;'
        env:
          PGPASSWORD: admin
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Gradle Build & Unit Tests
        run: ./gradlew build
        env:
          POSTGRES_URL: jdbc:postgresql://localhost:5432/banking_kata
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          MONGO_INITDB_ROOT_USERNAME: rootuser
          MONGO_INITDB_ROOT_PASSWORD: rootpass
          ME_CONFIG_MONGODB_ADMINUSERNAME: rootuser
          ME_CONFIG_MONGODB_ADMINPASSWORD: rootpass
          ME_CONFIG_MONGODB_SERVER: mongodb
          KEYCLOAK_REALM_URL: http://localhost:10000/auth/realms/banking-kata
          KEYCLOAK_TEST_CLIENT_ID: test-client
          KEYCLOAK_TEST_CLIENT_SECRET: B9N1WDFFMuZmYuEzXSbRC739YGaE7kb5
      - name: Gradle Integration Tests
        run: ./gradlew integrationTest
        env:
          POSTGRES_URL: jdbc:postgresql://localhost:5432/banking_kata
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          MONGO_INITDB_ROOT_USERNAME: rootuser
          MONGO_INITDB_ROOT_PASSWORD: rootpass
          ME_CONFIG_MONGODB_ADMINUSERNAME: rootuser
          ME_CONFIG_MONGODB_ADMINPASSWORD: rootpass
          ME_CONFIG_MONGODB_SERVER: mongodb
          KEYCLOAK_REALM_URL: http://localhost:10000/auth/realms/banking-kata
          KEYCLOAK_TEST_CLIENT_ID: test-client
          KEYCLOAK_TEST_CLIENT_SECRET: B9N1WDFFMuZmYuEzXSbRC739YGaE7kb5
